### ISSUE TITLE
html5-youtube.js with angular in meanjs

### ISSUE THREAD

**Issue by gethob** [ginpei/html5-youtube.js#10]
Dear ginpei,

I came accross your script, I like it is working good so far. I just have an issue if i execute the function in a controller of angularjs in meanjs, and I setup the player in a view template, it seems that even if the VideoId is correctly binded to the attribute data-youtube-video the youtube video is not loaded until I make a whole site refresh. Loading only a template view without refreshing the page results in no display of the video.

I would appreciate a hint from you.

Thank you.

**Comment by ginpei** [comment]
@gethob Hello! :smile_cat:  Thank you for gently reporting. It's exciting for me since I just started working with AngularJS a month ago.

I'm going to check it but I'm afraid that it'll take a couple of weeks to find time to figure it out because I'm really busy this week, unfortunately. I'd appreciate your waiting for me.

**Comment by gethob** [comment]
Thank you very much for your reply. Actually  worked for me when calling player._setupVideo({el: elPlayer});

**Comment by ginpei** [comment]
@gethob Oh so do you have no problems now?

**Comment by gethob** [comment]
Hi ginpei, thank you the workaround with calling player._setupVideo({el: elPlayer}) works good for me. If you may be would like to close this thread would be ok. many thanks

**Comment by ginpei** [comment]
I'm glad to hear that.
